Homework 2 is ready with maven+testng
lemmy90/NadezhdaLemekhova_LevelUp pull request #2
Opened 2022-06-11 16:19 UTC by lemmy90

Please, check my homework 2 with maven/testng

2022-06-15 18:06 UTC, khda91 requested changes
Исправь пожалуйста минорные комментарии

2022-06-15 18:06 UTC, khda91 commented on pom.xml
> +        <maven-compiler-plugin.encoding>UTF-8</maven-compiler-plugin.encoding>
Вот эта проперти лишняя, так как уже существует `project.source.encoding` и лучше использовать её

2022-06-15 18:06 UTC, khda91 commented on pom.xml
> +            <id>all-tests</id>
Вижу профайл только для всех тестов. Пожалуйста, посмотри внимательнее задание. Там сказано, что выбор сьюта осуществляется с помощью maven profile. Пока вижу только один профиль для одного сьюта, момента выбора как-то не чувствую)

2022-06-15 18:06 UTC, khda91 commented on src/test/java/ru/levelup/at/homework2/BaseDataProvider.java
> +public class BaseDataProvider {
Не очень хорошее имя для `DataProvider`. тут бы я его назвал как `SumDataProvider`, так как у тебя может быть много DataProviders для разных случаев метода суммы

2022-06-15 18:06 UTC, khda91 commented on src/test/java/ru/levelup/at/homework2/BaseCalcBeforeAfterHooksTest.java
> +public abstract class BaseCalcBeforeAfterHooksTest {
`BaseCalcTest`?

2022-06-15 19:08 UTC, lemmy90 commented on pom.xml
> +            <id>all-tests</id>
Fixed.

2022-06-15 19:08 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework2/BaseDataProvider.java
> +public class BaseDataProvider {
Fixed.

2022-06-15 19:08 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework2/BaseCalcBeforeAfterHooksTest.java
> +public abstract class BaseCalcBeforeAfterHooksTest {
Fixed.

2022-06-15 19:08 UTC, lemmy90 commented on pom.xml
> +        <maven-compiler-plugin.encoding>UTF-8</maven-compiler-plugin.encoding>
Fixed.

2022-06-17 18:11 UTC, khda91 approved these changes
Работа принята

2022-06-17 18:11 UTC, merged