Homework 3
lemmy90/NadezhdaLemekhova_LevelUp pull request #3
Opened 2022-06-21 19:22 UTC by lemmy90

Please, review homework 3. NOTE: check "Verify, что письмо исчезло из черновиков" wasn't done and commented in CrateNewLetterTest.class

2022-06-22 19:26 UTC, khda91 requested changes
А вот тесты не взлетают через `mvn clean test -P mailru-tests`
Исправить комментарии к работе

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] Suite file /Users/d.khodakovskiy/other-projects/LevelUp/2022/spring-2022-may/NadezhdaLemekhova_LevelUp/src/test/resources/ru/levelup/at/homework2/build/unit/testing/tools/suites/mailruTests.xml is not a valid file
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.908 s
[INFO] Finished at: 2022-06-22T21:36:17+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project nadezhda-lemekhova-spring-2022-may: 
[ERROR] 
[ERROR] Please refer to /Users/d.khodakovskiy/other-projects/LevelUp/2022/spring-2022-may/NadezhdaLemekhova_LevelUp/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Suite file /Users/d.khodakovskiy/other-projects/LevelUp/2022/spring-2022-may/NadezhdaLemekhova_LevelUp/src/test/resources/ru/levelup/at/homework2/build/unit/testing/tools/suites/mailruTests.xml is not a valid file
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Suite file /Users/d.khodakovskiy/other-projects/LevelUp/2022/spring-2022-may/NadezhdaLemekhova_LevelUp/src/test/resources/ru/levelup/at/homework2/build/unit/testing/tools/suites/mailruTests.xml is not a valid file
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:701)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +            .findElement(By.cssSelector("div > iframe[class ='ag-popup__frame__layout__iframe']"));
В целом тут `div` можно убрать, так как `iframe` у нас один на странице он тут не нужен

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement passwordField = wait.until(ExpectedConditions.elementToBeClickable(By.name("password")));
У тебя в `@BeforeMethod` заданы оба ожидания
```java
driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(60));
wait = new WebDriverWait(driver, Duration.ofSeconds(10));
```
Явное ожидание будет работать 60 секунд если у тебя элемент будет отсутсвовать на странице. 
Тут есть 2 варианта
1. Выбрать один тип ожиданий и его использовать
2. С помощью конструкции `try-finally` убрать неявное ожидание, и потом его вернуть обратно

Посмотри на другие места, где у тебя используются явные ожидания

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement toField = driver.findElement(By.xpath("//div[@class='contacts--1ofjA']//input"));
Я бы предложил заменить использование атрибута `@class` на атрибут `@data-type` так как он даст больше стабильности локатору

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement subjectField = driver.findElement(By.xpath("//div[@class='subject__wrapper--2mk6m']//input"));
`//input[@name='Subject']` не работает?

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +                    .xpath("//div[@class='layer-sent-page']/div/div/span[contains(@class, 'button2')]")));
`/div/div` можно убрать, чтобы збежать проблем с изменением DOM дерева в будущем

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +                .xpath("//div[@class='letter-body__body']"
как вариант поиграть с xpath. В дереве есть элемент с `data-signature-widget` фтрибутом. Можно найти его, и потом взять предыдущий элемент с помощью xpath фунцкий

Это если будет желание попробовать переписать немного этот локатор

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckLetterDeletionTest.java
> +        WebElement passwordField = wait.until(ExpectedConditions.elementToBeClickable(By.name("password")));
Про явные и неявные ожидания писал в классе `src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java`

Посмотри так же в нём комментарии к локаторам, скорее всего будут пересечения и тут есть аналогичные локаторы

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        WebElement passwordField = wait.until(ExpectedConditions.elementToBeClickable(By.name("password")));
Про явные и неявные ожидания писал в классе `src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java`

Посмотри так же в нём комментарии к локаторам, скорее всего будут пересечения и тут есть аналогичные локаторы

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +                 .invisibilityOfElementLocated(By.xpath("//span[text()='" + LETTER_TITLE + random + "']"))));*/
А тут у тебя никогда не будет работать, так как у тебя работаю неявные ожидания

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        Assert.assertTrue(newLetter.isDisplayed());
Проверку письма можно ещё осуществить следующим образом: 
1. Получить `List<WebElement>` всех писем (или их тем) на странице
2. Идти по этому списку, получать их текст и сравнивать с тем, что ты отправила
3. Как только письмо будет найдено выйти из цикла

2022-06-22 19:26 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        Assert.assertTrue(newLetter.isDisplayed());
Здесь `newLetter` нужно искать снова, чтобы всё работало как ожидается

2022-06-23 06:56 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +            .findElement(By.cssSelector("div > iframe[class ='ag-popup__frame__layout__iframe']"));
fixed.

2022-06-23 06:56 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement passwordField = wait.until(ExpectedConditions.elementToBeClickable(By.name("password")));
fixed.

2022-06-23 06:59 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement toField = driver.findElement(By.xpath("//div[@class='contacts--1ofjA']//input"));
fixed

2022-06-23 18:18 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement toField = driver.findElement(By.xpath("//div[@class='contacts--1ofjA']//input"));
к сожалению, в таком случае element not interactable. Оставляю как есть.

2022-06-23 18:18 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +        WebElement subjectField = driver.findElement(By.xpath("//div[@class='subject__wrapper--2mk6m']//input"));
к сожалению, в таком случае element not interactable. Оставляю как есть.

2022-06-23 18:20 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +                    .xpath("//div[@class='layer-sent-page']/div/div/span[contains(@class, 'button2')]")));
fixed

2022-06-23 18:21 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckLetterDeletionTest.java
> +        WebElement passwordField = wait.until(ExpectedConditions.elementToBeClickable(By.name("password")));
fixed

2022-06-23 18:21 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        WebElement passwordField = wait.until(ExpectedConditions.elementToBeClickable(By.name("password")));
fixed

2022-06-23 18:22 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +                .xpath("//div[@class='letter-body__body']"
А как у меня совсем плохо?

2022-06-23 18:24 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        Assert.assertTrue(newLetter.isDisplayed());
Так а сейчас же тоже работает. Или что ты имеешь ввиду?

2022-06-23 18:25 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        Assert.assertTrue(newLetter.isDisplayed());
Надо поменять или мой вариант тоже подходит?

2022-06-23 18:26 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +                 .invisibilityOfElementLocated(By.xpath("//span[text()='" + LETTER_TITLE + random + "']"))));*/
Да даже неявные убрав всё равно не работает :( так что оставила закомментированным

2022-06-24 17:41 UTC, khda91 approved these changes
работа принята

2022-06-24 17:43 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CheckCustomRuleTest.java
> +                .xpath("//div[@class='letter-body__body']"
Да нет, это просто как вариан поиграться с xpath

2022-06-24 17:43 UTC, khda91 commented on src/test/java/ru/levelup/at/homework3/CrateNewLetterTest.java
> +        Assert.assertTrue(newLetter.isDisplayed());
Этоо прросто как ещёё один вариант как можно искать п исьма

2022-06-24 17:44 UTC, merged