Homework 4
lemmy90/NadezhdaLemekhova_LevelUp pull request #4
Opened 2022-06-27 20:03 UTC by lemmy90

please, review

2022-06-29 15:37 UTC, khda91 requested changes
Исправь, пожалуйста, замечания

2022-06-29 15:37 UTC, khda91 commented on pom.xml
> +                        ${homework4.suite.base.dir}/${test.suite.name}
Для каждой домашней работы должен быть свой maven profile

2022-06-29 15:37 UTC, khda91 commented on src/main/java/ru/levelup/at/homework4/MailRuDraftLetterPage.java
> +    }
Конструктор можно вынести в базовый класс для всех страниц и потом от него наследоваться, чтобы уменьшить дублирование кода и держать общие параметры, такие как ожидание (например) едиными

2022-06-29 15:37 UTC, khda91 commented on src/main/java/ru/levelup/at/homework4/MailRuHomePage.java
> +public class MailRuHomePage {
Базовый класс

2022-06-29 15:37 UTC, khda91 commented on src/main/java/ru/levelup/at/homework4/MailRuMailboxHomePage.java
> +    WebElement trashFolder;
Группу всех этих элементов можно собрать в `List<WebElement>` и написать метод, который будет циклом пробегаться по всем элементам и кликать по нужному. Чтобы определить нужны на вход можно подавать имя папки, куда хотим перейти

2022-06-29 15:37 UTC, khda91 commented on src/main/java/ru/levelup/at/homework4/MailRuSentLetterPage.java
> +public class MailRuSentLetterPage {
Для Send можно не делать было бы отдельный Page Object, так как он полностью совпадает с inbox, Trash, Drafts и т.д.
В этих страницах меняется только содержимое, а именно письма, которые отображаются. Так что их все можно заменить на один Page Object

2022-06-29 15:37 UTC, khda91 commented on src/test/java/ru/levelup/at/homework4/AbstractBaseLettersTest.java
> +    protected static final String LETTER_BODY = "kak menya dostal xpath";
Не вижу properties файла для хранения кредов от почты

2022-06-29 18:23 UTC, lemmy90 commented on pom.xml
> +                        ${homework4.suite.base.dir}/${test.suite.name}
fixed

2022-06-29 18:28 UTC, lemmy90 commented on src/main/java/ru/levelup/at/homework4/MailRuSentLetterPage.java
> +public class MailRuSentLetterPage {
Он совпадает для инбаунда, для кастомной папки, но не для драфта, поэтому драфт выделен отдельно. Примеры:
Используется в инбаунд, кастомной папке:
sentLetterTitle = (xpath = "//h2[@class = 'thread-subject']")

Используется в драфте:
draftLetterTitle = (name = "Subject")

2022-06-29 18:58 UTC, lemmy90 commented on src/main/java/ru/levelup/at/homework4/MailRuDraftLetterPage.java
> +    }
fixed

2022-06-29 18:58 UTC, lemmy90 commented on src/main/java/ru/levelup/at/homework4/MailRuHomePage.java
> +public class MailRuHomePage {
fixed

2022-06-29 19:47 UTC, lemmy90 commented on src/main/java/ru/levelup/at/homework4/MailRuMailboxHomePage.java
> +    WebElement trashFolder;
опять же не подходит для кастомных папок. хз какой у неё айдишник

2022-07-01 08:45 UTC, lemmy90 commented on src/test/java/ru/levelup/at/homework4/AbstractBaseLettersTest.java
> +    protected static final String LETTER_BODY = "kak menya dostal xpath";
fixed

2022-07-17 20:30 UTC, khda91 approved these changes
Домашняя работа принята

2022-07-17 20:30 UTC, merged